---
title: "FP_318"
author: "Bryan Z"
date: "2024-04-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Final Project

```{r}
crashes_12 <- read_csv("https://raw.githubusercontent.com/bzamoram/Crashes_NYC_April_24/main/crashes_2012.csv")
crashes_12

crashes_13 <- read_csv("https://raw.githubusercontent.com/bzamoram/Crashes_NYC_April_24/main/crashes_2013.csv")
crashes_13

crashes_14 <- read_csv("https://raw.githubusercontent.com/bzamoram/Crashes_NYC_April_24/main/crashes_2014.csv")
crashes_14

crashes_15 <- read_csv("https://raw.githubusercontent.com/bzamoram/Crashes_NYC_April_24/main/crashes_2015.csv")
crashes_15

crashes_16 <- read_csv("https://raw.githubusercontent.com/bzamoram/Crashes_NYC_April_24/main/crashes_2016.csv")
crashes_16

crashes_17 <- read_csv("https://raw.githubusercontent.com/bzamoram/Crashes_NYC_April_24/main/crashes_2017.csv")
crashes_17

crashes_18 <- read_csv("https://raw.githubusercontent.com/bzamoram/Crashes_NYC_April_24/main/crashes_2018.csv")
crashes_18

crashes_19 <- read_csv("https://raw.githubusercontent.com/bzamoram/Crashes_NYC_April_24/main/crashes_2019.csv")
crashes_19

crashes_20 <- read_csv("https://raw.githubusercontent.com/bzamoram/Crashes_NYC_April_24/main/crashes_2020.csv")
crashes_20

crashes_21 <- read_csv("https://raw.githubusercontent.com/bzamoram/Crashes_NYC_April_24/main/crashes_2021.csv")
crashes_21

crashes_22 <- read_csv("https://raw.githubusercontent.com/bzamoram/Crashes_NYC_April_24/main/crashes_2022.csv")
crashes_22

crashes_23 <- read_csv("https://raw.githubusercontent.com/bzamoram/Crashes_NYC_April_24/main/crashes_2023.csv")
crashes_23

crashes_24 <- read_csv("https://raw.githubusercontent.com/bzamoram/Crashes_NYC_April_24/main/crashes_2024.csv")
crashes_24

```


```{r}
table(str_match(crashes$CRASH.DATE,"\\d{4}"))
```

```{r}
crashes <- crashes |> 
  mutate(year = str_match(CRASH.DATE,"\\d{4}")[,1])
```

```{r}
for (year_ch in as.character(2012:2024)) {
  crashes_filter <- crashes |> filter(year == year_ch)
  write.csv(crashes_filter, paste0("crashes_",year_ch,".csv"))
}
```
```{r}
as.character(2012:2024)
```

